### PR TITLE
Handled team_join to prompt introduction per #2.

### PR DESCRIPTION
**Pull request by agentmirv**
Hopefully this works, I added comments with some assumptions I made.

### CODE REVIEW

**Comment by JoeDuncko** [comment]
Looks like this also contains the changes made in https://github.com/codeyoungstown/code-youngstown-slack-bot/pull/4 . So I'll close that one and just merge and test this one.

Thanks so much for taking a shot at this!

closes #2

**Comment by JoeDuncko** [comment]
closes #4

**Comment by JoeDuncko** [comment]
Added `team_join` as both a Workspace Event and a Bot Event

image

**Comment by JoeDuncko** [comment]
Reinstalled the app

**Comment by JoeDuncko** [comment]
// 1) Administration -> Manage Apps -> Remove
// 2) Administration -> Manage Apps -> Install

Invited the bot to `#waywo` and `#intro`

**Comment by agentmirv** [comment]
Sweet, yeah it's my first pull request on github so I'm still figuring out the contributing thing.

**Pull request merged**
